### ISSUE TITLE
Rewrite ConnectorModule.java in Swift

### ISSUE THREAD

**Issue by jdpigeon** [NeuroTechX/eeg-101#12]
We've got the Muse SDK integrated into our app so our first step for the port is to port our connection code over to Swift.

Code to be ported:
https://github.com/NeuroTechX/eeg-101/blob/master/EEG101/android/app/src/main/java/com/eeg_project/components/connector/ConnectorModule.java

iOS Native Module documentation:
https://facebook.github.io/react-native/docs/native-modules-ios.html

**Comment by jdpigeon** [comment]
I just totally rewrote ConnectorModule in Java to make it a lot more efficient and readable. Keep this in mind

**Comment by nuKs** [comment]
Hello,

Any news on this?

**Comment by jdpigeon** [comment]
Yea!

We've been working pretty hard on porting EEG 101 over to iOS in the last few months. The connector module has been a bit tricky for us because of all the bridging between React Native and Swift. However, me and @tmcneely will hopefully be able to dedicate some time to figuring out and completing this part of the port very soon.

**Comment by nuKs** [comment]
Thanks for the quick feedback.

I've started working on these:
https://github.com/nuKs/podspec-libmuse
https://github.com/nuKs/react-native-eegmuselib

I'll get back to you once I get something useful.

(ftr: repos may move to https://github.com/bimslab in the near future)

**Comment by jdpigeon** [comment]
Check out what we've done here: https://github.com/NeuroTechX/eeg-101/tree/iOS

**Comment by nuKs** [comment]
Great work! Thanks for getting back to me.

I'ld really like to fork your project and start from it as a basis for our research app instead of keeping on my own. Hope it's fine with you. 

Ftr, we plan to develop a few simple features, perhaps an oddball task with some server-side processing.

**Comment by jdpigeon** [comment]
Hey @nuKs that sounds amazing!

Your use case is one of the reasons we created and this app and developed it completely open source. We would be honoured if you forked this project. I'd also be happy to answer any questions about how the code base works and how to integrate the work you've already done.

BTW, ERPs are the next lesson that we are looking forward to developing for the app this year. We're very interested in getting an oddball task going in the app and would love if any work you did made it back to EEG 101.

**Comment by nuKs** [comment]
I've joined the neurotechx slack channel. 

Your code looks quite clean, I shouldn't have any issue. I'll probably only start working seriously next week.  

I'll keep the structure of my code compatible with yours.

The app focuses on daily assessment of symptoms in schizophrenia in a longitudinal intensive study
I have first to integrate these few features:
- Question / Answer module
- Automatic send of data when wifi connection is detected

I'll probably do the oddball after, the lab is not absolutely sure to go this way yet (but nearly). In case you have interest in these feature as well and have special requirements, let me know, I'll try to match these.

We're also interested in integrating eye tracking from mobile camera, although this looks tricky. Any info is welcome !
