### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by kowalej** [NeuroTechX/eeg-101#22]
Application should be localized to support wider, international user base. Can make use of : https://github.com/AlexanderZaytsev/react-native-i18n. 

Text should be centralized to translation files for each target language and referenced accordingly using key identifiers. 

Suggested languages to begin: English, French, and Spanish.

**Comment by jdpigeon** [comment]
Localization framework has been setup. Next goal will be to translate lesson content into French and Spanish. Need a spanish speaker!

**Comment by jdpigeon** [comment]
@hubertjb is going to do the French translation.

Raymundo(?) from MTL or Hector is going to do the Spanish translation.

**Comment by neurohazardous** [comment]
@jdpigeon Hey, yes, I think the best would be to have both me and Ray work on the Spanish translation so we can have some kind of cross validation of technical terms and such

**Comment by hubertjb** [comment]
I talked with @rcassani and he would be willing to help with the Spanish translation along with you @neurohazardous! :)

The localization files can be found here: https://github.com/NeuroTechX/eeg-101/tree/master/EEG101/src/i18n/locales. I think it would be a good idea to make a spreadsheet where we can keep all three languages together in separate columns, to help with the translation process (I'm hoping the French and Spanish versions can inform each other). What do you think?

**Comment by hubertjb** [comment]
@kowalej informed me that we already have a spreadsheet for that purpose (https://github.com/NeuroTechX/eeg-101/blob/master/translation_text.ods). It's also automated, so that once text is updated we can just copy-paste the results into the localization files.

**Comment by rcassani** [comment]
@hubertjb, great!

**Comment by neurohazardous** [comment]
@hubertjb sounds like a plan; I talked to @rcassani and we will start working on it this week. Should be done in a couple of weeks :D

**Comment by jdpigeon** [comment]
Spanish is down!

Three to go?

French
German
Mandarin

**Comment by dennlinger** [comment]
I'm working on German right now, maybe halfway through.
Should be done with it either this weekend or sometime during the next week :)

**Comment by jdpigeon** [comment]
French, German, Spanish down!!

Chinese and Hindi to gooooo :earth_asia:
