### ISSUE TITLE
Classifier data visualization

### ISSUE THREAD

**Issue by jdpigeon** [NeuroTechX/eeg-101#27]
In order to help users understand the ML process, we should visualize some important data behind the classifier trained in the BCI screens.

This should probably include:
- a line plot showing the relative importance of all the features used to train the GNB
- a clustered xy plot to show the seperation of features

**Comment by jdpigeon** [comment]
Built line plot in Victory (MiniChart)

**Comment by jdpigeon** [comment]
@hubertjb, need some more clarification on what data a scatter plot (to show clustering) should contain.

Also, I will be changing the feature ranking plot from rankings to importance in an upcoming update

**Comment by hubertjb** [comment]
@jdpigeon this is what I had in mind:

![scatterplot](https://user-images.githubusercontent.com/6500858/28501635-fb341834-6fad-11e7-967d-5baa17b2ba1f.png)

```
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

class1 = np.random.multivariate_normal([1, 2], [[1, 0], [0, 0.5]], 30)
class2 = np.random.multivariate_normal([2, 1], [[1, 0], [0, 0.5]], 30)

fig, ax = plt.subplots()
ax.scatter(class1[:, 0], class1[:, 1], label='class 1')
ax.scatter(class2[:, 0], class2[:, 1], label='class 2')
ax.set_xlabel('First best feature')
ax.set_ylabel('Second best feature')
plt.legend()
```

**Comment by jdpigeon** [comment]
We've currently got a stacked bar chart to show feature importance, but a scatter plot would be nice in the future. Maybe a good intro to Victory Native for @jeejung?

**Comment by jeejung** [comment]
Sounds good, @jdpigeon. I'll take a look at this tonight.

**Comment by vasyl91** [comment]
Just finished csv reader based on androidplot (screen shows random data for tests). Will it be suitable?
![screenshot_2019-02-09-23-06-45-429_com sleep_tracker](https://user-images.githubusercontent.com/42324650/52534101-7de62300-2d3d-11e9-8106-71b1dc718fa0.png)

**Comment by jdpigeon** [comment]
Hey @vasyl91,

Our idea with this data visualization was to show how epochs of EEG data can be clustered based on two different dimensions. For that, a line plot won't really work. Maybe we could look into [AndroidPlot's scatter plot?](https://github.com/halfhp/androidplot/blob/master/demoapp/src/main/java/com/androidplot/demos/ScatterPlotActivity.java)

**Comment by vasyl91** [comment]
I know, line plot on screenshot is just an example. Main thing is reading data from CSV file and converting it to graph. Adjusting it to scatter plot shouldn't be a big deal ;) I can share working RN module if you want

**Comment by jdpigeon** [comment]
That'd be amazing! Keep in my mind though, the data we want to display regarding the state of the classifier doesn't have to come from a CSV file, but just from the data stored in the `ClassifierModule` class.
