### ISSUE TITLE
Can't send recorded EEG data through Gmail or Inbox

### ISSUE THREAD

**Issue by jdpigeon** [NeuroTechX/eeg-101#35]
Sometimes when trying to send recorded EEG data from the Sandbox screen to an email address there won't be any attachment and the warning "Can't attach empty file"

This seems to be a problem with Android 6.0 and Gmail's storage access permissions: https://stackoverflow.com/questions/32318692/android-attaching-a-file-to-gmail-cant-attach-empty-file

To fix, go into  Settings->Apps->Gmail->Permissions and enable the "Storage" permission manually

**Comment by matteogithub** [comment]
Hi, is it possible to send recorded EEG data from the Sandbox?

**Comment by jdpigeon** [comment]
Yes! The red record button on the Sandbox screen should allow you to record data. If you click the red button once it's turned into a square you should see a sharing options pop up that allows you to send your data as a .csv to an email address
