### ISSUE TITLE
Ending recording session in EEG Sandbox crashes app

### ISSUE THREAD

**Issue by jdpigeon** [NeuroTechX/eeg-101#55]
Probably due to this error reported in developer console:
`android.os.FileUriExposedException:`
`at com.eeg_project.components.csv.EEGFileWriter.sendData (EEGFileWriter.java:114)`

**Comment by rohitrangwani** [comment]
Have to switch using content URI : https://developer.android.com/reference/android/os/FileUriExposedException.html.

**Comment by jdpigeon** [comment]
Fixed in most recent commit: https://github.com/NeuroTechX/eeg-101/commit/ec1587856c7aa12ec04cffc39d858d02034f28da
