### ISSUE TITLE
Battery indicator

### ISSUE THREAD

**Issue by vasyl91** [NeuroTechX/eeg-101#64]
Would you consider implementing battery indicator?

**Comment by jdpigeon** [comment]
That's a great idea, probably not too much work since the battery information is obtainable through the Muse SDK. We'll keep this addition in mind as we start developing the app again.

**Comment by vasyl91** [comment]
Splendid ;) if I may ask, when are you planning to start developing app again?

**Comment by jdpigeon** [comment]
That's up in the air, but the plan is for development to start sometime before the end of the year. @tmcneely will be the main developer

**Comment by vasyl91** [comment]
Ok, jobs done! After many trials and errors (I'm not professional programmer) I managed to add battery indicator to the project I'm working on ;) I also adjusted it to EEG101. That's my little contribution and way to say thank you for sharing your app. 

EDIT: everything is few comments below.

**Comment by jdpigeon** [comment]
Amazing! Would you be comfortable making a pull request with your battery indicator? That way we can add it to the app :tada:

**Comment by vasyl91** [comment]
Ofc, I'll check some things and will do that this evening ;)

EDIT: Just fixed an error (previously navbar didn't update battery status).  Checked it, seems to work just fine.

Screenshots:
[Screenshots.zip](https://github.com/NeuroTechX/eeg-101/files/2600349/Screenshots.zip)

EDIT2: Pulled request. You can close this issue ;)

EDIT3: Fixed another error that slowed down whole app. Now works fine (left app connected for the whole night).
Download:
[BatteryIndicator.zip](https://github.com/NeuroTechX/eeg-101/files/2604606/BatteryIndicator.zip)

**Comment by vasyl91** [comment]
I found 1st issue - indicator appears only after user taps on the menu icon. Don't know why I'll try to fix this, however for the time being I've no clue. Anyway pulling request seems to be more complicated than I thought, I'll try to go through that during following weekend
